playlists:
  Marvel Cinematic Universe:
    sync_mode: sync
    libraries: Movies, TV Shows
    tvdb_list: https://www.thetvdb.com/lists/marvel-cinematic-universe
    summary: Marvel Cinematic Universe
    sync_to_users: ImDevinC, dagreatdennis
    url_poster: https://theposterdb.com/api/assets/26227
  Bedtime:
    sync_mode: sync
    libraries: Movies, TV Shows
    tvdb_list: https://www.thetvdb.com/lists/17041
    summary: Bedtime playlist
    sync_to_users: ImDevinC
    url_poster: https://raw.githubusercontent.com/ImDevinC/plex-meta-manager-configs/refs/heads/main/assets/playlist-goodnight.png
  "Gundam: Universal Century":
    sync_mode: sync
    libraries: Movies, Anime
    tvdb_list: https://thetvdb.com/lists/17159
    summary: Gundam Universal Century in release order
    sync_to_users: ImDevinC
    url_poster: https://theposterdb.com/api/assets/140595
